from bot.base.resource import Template

UMAMUSUME_UI_TEMPLATE_PATH = "/umamusume/ui"
UMAMUSUME_BTN_TEMPLATE_PATH = "/umamusume/btn"
UMAMUSUME_REF_TEMPLATE_PATH = "/umamusume/ref"
UMAMUSUME_UMA_ICON_TEMPLATE_PATH = "/umamusume/uma_icon"

UI_INFO = Template("INFO", UMAMUSUME_UI_TEMPLATE_PATH)
UI_MAIN_MENU = Template("MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_MAIN_MENU = Template("CULTIVATE_MAIN_MENU", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_TRAINING_SELECT = Template("CULTIVATE_TRAINING_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_TRAINING_SELECT_1 = Template("CULTIVATE_TRAINING_SELECT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_SCENARIO_SELECT = Template("CULTIVATE_SCENARIO_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_FOLLOW_SUPPORT_CARD_SELECT = Template("CULTIVATE_FOLLOW_SUPPORT_CARD_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_SUPPORT_CARD_SELECT = Template("CULTIVATE_SUPPORT_CARD_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EXTEND_UMAMUSUME_SELECT = Template("CULTIVATE_EXTEND_UMAMUSUME_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_UMAMUSUME_SELECT = Template("CULTIVATE_UMAMUSUME_SELECT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_FINAL_CHECK = Template("CULTIVATE_FINAL_CHECK", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_EVENT_UMAMUSUME = Template("CULTIVATE_EVENT_UMAMUSUME", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EVENT_SUPPORT_CARD = Template("CULTIVATE_EVENT_SUPPORT_CARD", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_EVENT_SCENARIO = Template("CULTIVATE_EVENT_SCENARIO", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_GOAL_RACE_1 = Template("CULTIVATE_GOAL_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_GOAL_RACE_2 = Template("CULTIVATE_GOAL_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_1 = Template("CULTIVATE_URA_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_2 = Template("CULTIVATE_URA_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_URA_RACE_3 = Template("CULTIVATE_URA_RACE_3", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RACE_LIST_1 = Template("CULTIVATE_RACE_LIST_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RACE_LIST_2 = Template("CULTIVATE_RACE_LIST_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_BEFORE_RACE_1 = Template("BEFORE_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_BEFORE_RACE_2 = Template("BEFORE_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_IN_RACE_UMA_LIST_1 = Template("IN_RACE_UMA_LIST_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_IN_RACE_UMA_LIST_2 = Template("IN_RACE_UMA_LIST_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_IN_RACE_1 = Template("IN_RACE_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_IN_RACE_2 = Template("IN_RACE_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_RACE_RESULT_1 = Template("RACE_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_RESULT_2 = Template("RACE_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_REWARD_1 = Template("RACE_REWARD_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RACE_REWARD_2 = Template("RACE_REWARD_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_GOAL_ACHIEVED = Template("GOAL_ACHIEVED", UMAMUSUME_UI_TEMPLATE_PATH)
UI_GOAL_FAILED = Template("GOAL_FAILED", UMAMUSUME_UI_TEMPLATE_PATH)
UI_NEXT_GOAL = Template("NEXT_GOAL", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ALL_GOAL_ACHIEVED = Template("ALL_GOAL_ACHIEVED", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_EXTEND = Template("CULTIVATE_EXTEND", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT = Template("CULTIVATE_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT_1 = Template("CULTIVATE_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_RESULT_2 = Template("CULTIVATE_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_CATCH_DOLL_GAME_1 = Template("CULTIVATE_CATCH_DOLL_GAME_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_CATCH_DOLL_GAME_2 = Template("CULTIVATE_CATCH_DOLL_GAME_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_CATCH_DOLL_GAME_RESULT_1 = Template("CULTIVATE_CATCH_DOLL_GAME_RESULT_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_CATCH_DOLL_GAME_RESULT_2 = Template("CULTIVATE_CATCH_DOLL_GAME_RESULT_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_LEARN_SKILL_1 = Template("CULTIVATE_LEARN_SKILL_1", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_LEARN_SKILL_2 = Template("CULTIVATE_LEARN_SKILL_2", UMAMUSUME_UI_TEMPLATE_PATH)

UI_CULTIVATE_FINISH = Template("CULTIVATE_FINISH", UMAMUSUME_UI_TEMPLATE_PATH)
UI_RECEIVE_CUP = Template("RECEIVE_CUP", UMAMUSUME_UI_TEMPLATE_PATH)
UI_CULTIVATE_LEVEL_RESULT = Template("CULTIVATE_LEVEL_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_FACTOR_RECEIVE = Template("FACTOR_RECEIVE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_HISTORICAL_RATING_UPDATE = Template("HISTORICAL_RATING_UPDATE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_SCENARIO_RATING_UPDATE = Template("SCENARIO_RATING_UPDATE", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ACTIVITY_RESULT = Template("ACTIVITY_RESULT", UMAMUSUME_UI_TEMPLATE_PATH)
UI_ACTIVITY_REWARD = Template("ACTIVITY_REWARD", UMAMUSUME_UI_TEMPLATE_PATH)

REF_SUPPORT_CARD_TYPE_SPEED = Template("SUPPORT_CARD_TYPE_SPEED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_STAMINA = Template("SUPPORT_CARD_TYPE_STAMINA", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_POWER = Template("SUPPORT_CARD_TYPE_POWER", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_WILL = Template("SUPPORT_CARD_TYPE_WILL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_INTELLIGENCE = Template("SUPPORT_CARD_TYPE_INTELLIGENCE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUPPORT_CARD_TYPE_FRIEND = Template("SUPPORT_CARD_TYPE_FRIEND", UMAMUSUME_REF_TEMPLATE_PATH)


REF_TRAINING_TYPE_SPEED = Template("TRAINING_TYPE_SPEED", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_STAMINA = Template("TRAINING_TYPE_STAMINA", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_POWER = Template("TRAINING_TYPE_POWER", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_WILL = Template("TRAINING_TYPE_WILL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_TRAINING_TYPE_INTELLIGENCE = Template("TRAINING_TYPE_INTELLIGENCE", UMAMUSUME_REF_TEMPLATE_PATH)

REF_MOTIVATION_1 = Template("MOTIVATION_1", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_2 = Template("MOTIVATION_2", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_3 = Template("MOTIVATION_3", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_4 = Template("MOTIVATION_4", UMAMUSUME_REF_TEMPLATE_PATH)
REF_MOTIVATION_5 = Template("MOTIVATION_5", UMAMUSUME_REF_TEMPLATE_PATH)

MOTIVATION_LIST = [REF_MOTIVATION_1, REF_MOTIVATION_2, REF_MOTIVATION_3, REF_MOTIVATION_4, REF_MOTIVATION_5]

REF_CULTIVATE_SUPPORT_CARD_EMPTY = Template("CULTIVATE_SUPPORT_CARD_EMPTY", UMAMUSUME_REF_TEMPLATE_PATH)
REF_FOLLOW_SUPPORT_CARD_DETECT_LABEL = Template("FOLLOW_SUPPORT_CARD_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SELECTOR = Template("SELECTOR", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_GOAL_RACE = Template("RACE_LIST_GOAL_RACE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_URA_RACE = Template("RACE_LIST_URA_RACE", UMAMUSUME_REF_TEMPLATE_PATH)
REF_RACE_LIST_DETECT_LABEL = Template("RACE_LIST_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SKILL_LIST_DETECT_LABEL = Template("SKILL_LIST_DETECT_LABEL", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SKILL_LEARNED = Template("SKILL_LEARNED", UMAMUSUME_REF_TEMPLATE_PATH)

REF_DEBUT_RACE_NOT_WIN = Template("DEBUT_RACE_NOT_WIN", UMAMUSUME_REF_TEMPLATE_PATH)
REF_SUITABLE_RACE = Template("SUITABLE_RACE", UMAMUSUME_REF_TEMPLATE_PATH)

URA_DATE_1 = Template("URA_DATE_1", UMAMUSUME_REF_TEMPLATE_PATH)
URA_DATE_2 = Template("URA_DATE_2", UMAMUSUME_REF_TEMPLATE_PATH)

BTN_SKIP = Template("SKIP", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_SKIP_OFF = Template("SKIP_OFF", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_SKIP_SPEED_1 = Template("SKIP_SPEED_1", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_SKIP_SPEED_2 = Template("SKIP_SPEED_2", UMAMUSUME_BTN_TEMPLATE_PATH)
BTN_CLOSE = Template("CLOSE", UMAMUSUME_BTN_TEMPLATE_PATH)

UMA_ICON_URA_NPC_1 = Template("URA_NPC_1", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)
UMA_ICON_URA_NPC_2 = Template("URA_NPC_2", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)
UMA_ICON_FRIEND_1 = Template("FRIEND_1", UMAMUSUME_UMA_ICON_TEMPLATE_PATH)


